In [1]:
import numpy as np

a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [ ]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

#陳列運算
a + b

array([ 3,  7, 11, 15, 19])

In [10]:
#2維陣列
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.ndim #維度
arr.shape  #形狀：在外面是第一維，裡面是第二維
arr.size  #總共有幾個元素
arr.dtype  #資料型態


dtype('int64')

In [13]:
np.random.rand()
np.random.rand(30, 4)

array([[0.1552634 , 0.49419903, 0.948057  , 0.382936  ],
       [0.64565985, 0.50513083, 0.14270247, 0.34038988],
       [0.53824321, 0.10991446, 0.60779562, 0.17682458],
       [0.96549663, 0.2541359 , 0.38338284, 0.61655951],
       [0.15274124, 0.32420271, 0.25353073, 0.45145857],
       [0.28160016, 0.58370869, 0.19176369, 0.3674672 ],
       [0.182221  , 0.00933756, 0.30851584, 0.59752659],
       [0.1315618 , 0.72600462, 0.17981204, 0.26515887],
       [0.37114006, 0.67477259, 0.2822074 , 0.43427311],
       [0.45925216, 0.33547865, 0.22490732, 0.48236506],
       [0.34579988, 0.41419674, 0.70922327, 0.01512463],
       [0.26886884, 0.15463683, 0.58648459, 0.41730641],
       [0.43401369, 0.3083951 , 0.98516285, 0.66395459],
       [0.13464265, 0.93542445, 0.69462491, 0.60219431],
       [0.01884431, 0.91686569, 0.27039057, 0.6676913 ],
       [0.86986124, 0.68654251, 0.39967091, 0.63189525],
       [0.7599352 , 0.79050615, 0.46722858, 0.79295206],
       [0.74680302, 0.71547118,

In [16]:
scores = np.random.randint(50, 101, size=(50, 5))  #產生50列5行的陣列，數字介於50到100之間
scores

array([[ 76,  59,  73,  53,  51],
       [ 90,  78,  76,  54,  98],
       [ 83,  76,  94,  78,  87],
       [ 91,  52,  69,  75,  80],
       [ 83,  72,  63,  63,  52],
       [ 76,  87,  63,  63,  99],
       [ 86,  54,  75,  56,  80],
       [ 79,  70,  70,  99,  93],
       [ 77, 100,  79,  91,  69],
       [ 56,  99,  69,  76,  69],
       [ 64,  98,  64,  62,  83],
       [ 76,  61,  56,  59,  85],
       [ 88,  82,  99,  73,  57],
       [ 75,  82,  70,  57,  91],
       [ 90,  96,  61,  67,  59],
       [ 68,  90,  78,  82,  77],
       [ 74,  55,  95,  75,  73],
       [ 53,  97,  52,  52,  90],
       [ 60,  91,  67,  63,  53],
       [ 86,  90, 100,  57,  51],
       [ 76,  89,  64,  56,  94],
       [ 86,  63,  65,  73,  62],
       [ 79,  89,  78,  59,  97],
       [ 52,  87,  88,  55,  72],
       [ 88,  82,  83,  56,  89],
       [ 80,  67,  63,  83,  92],
       [ 81,  59,  57,  63,  79],
       [ 67,  62,  76,  79,  69],
       [ 71,  95,  76,  76,  91],
       [ 81,  