In [3]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
#索引
arr[1]

#一維的slice
arr[:5] #前5個
arr[-5:] #最後5個

array([50, 60, 70, 80, 90])

In [7]:
scores = np.random.randint(50, 100, size=(50, 5))
scores

array([[80, 56, 96, 53, 95],
       [58, 54, 89, 76, 59],
       [93, 93, 55, 93, 97],
       [96, 59, 86, 97, 66],
       [70, 74, 94, 61, 54],
       [75, 59, 66, 80, 81],
       [66, 55, 69, 93, 86],
       [55, 99, 96, 63, 62],
       [80, 70, 53, 76, 64],
       [94, 60, 59, 73, 65],
       [90, 54, 75, 72, 96],
       [76, 85, 54, 69, 86],
       [82, 69, 94, 58, 62],
       [83, 71, 92, 97, 86],
       [52, 68, 76, 84, 60],
       [76, 97, 95, 89, 93],
       [58, 54, 97, 82, 84],
       [68, 89, 92, 55, 86],
       [70, 55, 96, 83, 62],
       [59, 94, 90, 63, 93],
       [50, 72, 79, 58, 87],
       [67, 56, 65, 88, 94],
       [93, 62, 65, 52, 76],
       [65, 81, 74, 96, 62],
       [94, 65, 66, 75, 56],
       [60, 99, 70, 69, 68],
       [72, 92, 88, 54, 60],
       [62, 69, 92, 81, 61],
       [87, 72, 70, 64, 52],
       [98, 58, 51, 68, 50],
       [81, 65, 86, 62, 60],
       [73, 68, 63, 88, 64],
       [99, 60, 76, 60, 83],
       [51, 97, 86, 68, 68],
       [58, 59

In [ ]:
scores = np.random.randint(50, 100, size=(50, 5))
scores[0] #shape (5,)
scores[0, :]  #第一列所有行
scores[0:1, :] #(1, 5) shape

(5,)

In [12]:
#前5個學生
scores[:5, :]
#前5個學生的前3科成績
scores[:5, :3]

array([[77, 86, 98],
       [60, 94, 87],
       [89, 90, 51],
       [70, 73, 57],
       [54, 50, 57]], dtype=int32)

In [15]:
#第一科的分數
scores[:, 0]
#第二科的分數
scores[:, 1]
#第三科的分數
scores[:, 2]

array([98, 87, 51, 57, 57, 78, 56, 69, 61, 66, 63, 61, 75, 95, 91, 85, 74,
       98, 90, 62, 82, 63, 62, 59, 80, 82, 98, 98, 54, 78, 85, 67, 80, 92,
       88, 99, 77, 90, 53, 59, 81, 85, 57, 94, 62, 85, 58, 52, 53, 78],
      dtype=int32)

In [ ]:
#ndarray可以陳列運算
#所有人的總分
total = scores[:, 0] + scores[:, 1] + scores[:, 2] + scores[:, 3] + scores[:, 4]
total

array([422, 360, 349, 350, 322, 359, 330, 379, 429, 394, 367, 335, 384,
       366, 411, 453, 373, 365, 382, 319, 381, 333, 412, 305, 366, 358,
       391, 409, 346, 358, 419, 371, 317, 365, 371, 375, 356, 369, 382,
       387, 390, 374, 319, 408, 327, 421, 357, 388, 346, 349], dtype=int32)

In [17]:
total/5

array([84.4, 72. , 69.8, 70. , 64.4, 71.8, 66. , 75.8, 85.8, 78.8, 73.4,
       67. , 76.8, 73.2, 82.2, 90.6, 74.6, 73. , 76.4, 63.8, 76.2, 66.6,
       82.4, 61. , 73.2, 71.6, 78.2, 81.8, 69.2, 71.6, 83.8, 74.2, 63.4,
       73. , 74.2, 75. , 71.2, 73.8, 76.4, 77.4, 78. , 74.8, 63.8, 81.6,
       65.4, 84.2, 71.4, 77.6, 69.2, 69.8])

In [ ]:
np.sum(scores, axis=1)  #每個學生的總分
np.mean(scores, axis=1)  #每個學生的平均分

In [20]:
scores.sum(axis=1) #每個學生的總分：實體方法
scores.mean(axis=1) #每個學生的平均分：實體方法

array([84.4, 72. , 69.8, 70. , 64.4, 71.8, 66. , 75.8, 85.8, 78.8, 73.4,
       67. , 76.8, 73.2, 82.2, 90.6, 74.6, 73. , 76.4, 63.8, 76.2, 66.6,
       82.4, 61. , 73.2, 71.6, 78.2, 81.8, 69.2, 71.6, 83.8, 74.2, 63.4,
       73. , 74.2, 75. , 71.2, 73.8, 76.4, 77.4, 78. , 74.8, 63.8, 81.6,
       65.4, 84.2, 71.4, 77.6, 69.2, 69.8])